---
version: "3"
services:
  wbcc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output/:/output/
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root # not good
      MYSQL_DATABASE: wbcc
      MYSQL_USER: wbcc
      MYSQL_PASSWORD: password # also not good
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      # - ./my.cnf/:/etc/mysql/conf.d/
